### ISSUE TITLE
Dumping problem

### ISSUE THREAD

**Issue by AamirBuneri** [k493r0/EqManage#6]
Error
SQL query:

--
-- Dumping data for table `users`
--

-- REDACTED

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`),
  ADD UNIQUE KEY `categoryName` (`categoryName`)
MySQL said: Documentation

#1071 - Specified key was too long; max key length is 767 bytes

I am not a professional learning but i am facing this issue

**Comment by k493r0** [comment]
Sorry, I don't maintain this code any more, but just looking at the error suggests one of following:

Index Length Limit: By default, MySQL's InnoDB storage engine (commonly used) has a maximum index length of 767 bytes. You're likely exceeding this limit with one of the keys you're trying to create.

Character Set: The size of a character in bytes depends on the character set used for your table. For instance, UTF-8mb4 uses 4 bytes per character, while UTF-8 uses 3. If the `id` or `categoryName` columns use a multi-byte character set like UTF-8mb4, the effective length for indexing is reduced hence might be hitting that limit
